AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AlexaShoppingList:
    Default: Alexa shopping list
    Type: String
  CustomEndpoint:
    Type: String
  SkillId:
    Type: String
  SkillClientId:
    Type: String
  SkillClientSecret:
    Type: String
  LambdaFunctionName:
    Default: alexa-lists-event-forwarder
    Type: String
  LambdaRuntime:
    Type: String
  LambdaHandler:
    Type: String
  CodeBucket:
    Type: String
  CodeKey:
    Type: String
  CodeVersion:
    Type: String
Mappings:
  RegionalMap:
    us-east-1:
      AlexaApiUrl: https://api.amazonalexa.com
      LwaApiUrl: https://api.amazon.com
    eu-west-1:
      AlexaApiUrl: https://api.eu.amazonalexa.com
      LwaApiUrl: https://api.amazon.co.uk
    us-west-2:
      AlexaApiUrl: https://api.fe.amazonalexa.com
      LwaApiUrl: https://api.amazon.co.jp
Resources:
  AlexaSkillIAMRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: AlexaListsSync
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionName}:*
                - Effect: Allow
                  Action:
                    - lambda:AddPermission
                    - lambda:RemovePermission
                  Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunctionName}
  AlexaSkillFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
        S3ObjectVersion: !Ref CodeVersion
      FunctionName: !Ref LambdaFunctionName
      Description: OurGroceries List Sync with Alexa
      Handler: !Ref LambdaHandler
      Runtime: !Ref LambdaRuntime
      Role: !GetAtt AlexaSkillIAMRole.Arn
      MemorySize: 128
      Timeout: 20
      Environment:
        Variables:
          ALEXA_API_URL: !FindInMap [ RegionalMap, !Ref AWS::Region, AlexaApiUrl ]
          ALEXA_SHOPPING_LIST: !Ref AlexaShoppingList
          LWA_API_URL: !FindInMap [ RegionalMap, !Ref AWS::Region, LwaApiUrl ]
          CUSTOM_ENDPOINT: !Ref CustomEndpoint
          SKILL_ID: !Ref SkillId
          SKILL_CLIENT_ID: !Ref SkillClientId
          SKILL_CLIENT_SECRET: !Ref SkillClientSecret
  AlexaSkillFunctionEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt AlexaSkillFunction.Arn
      Principal: alexa-appkit.amazon.com
      EventSourceToken: !Ref SkillId
  AlexaSkillFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AlexaSkillFunction}
      RetentionInDays: 30
Outputs:
  SkillEndpoint:
    Description: LambdaARN for the regional endpoint
    Value: !GetAtt AlexaSkillFunction.Arn
